# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-23 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SIS', '0002_auto_20160723_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.IntegerField(choices=[(1, 'Computer Science & Engineering'), (2, 'Electrical Engineering'), (3, 'Civil Engineering'), (4, 'Others')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
