# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-26 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0004_auto_20160723_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(default=0)),
                ('Date', models.DateField()),
                ('present', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave', models.IntegerField(default=7)),
                ('earned_leave', models.IntegerField(default=10)),
                ('sick_leave', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Pending')], default=3)),
                ('reason', models.CharField(max_length=900)),
                ('verdict', models.CharField(max_length=900, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='department',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='attendance',
            new_name='current_marks',
        ),
        migrations.AddField(
            model_name='student',
            name='inter_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjects',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaches', to='SIS.Faculty'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='SIS.Faculty'),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='SIS.Faculty'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='SIS.Student'),
        ),
    ]
