# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-26 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0005_auto_20160727_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='inter_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='tenth_marks',
            field=models.FloatField(default=0),
        ),
    ]
