# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-26 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0006_auto_20160727_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='date',
            new_name='end',
        ),
    ]
