# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-31 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0007_auto_20160727_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='type',
            field=models.IntegerField(choices=[(1, 'Sick'), (2, 'Casual'), (3, 'Earned')], default=3),
        ),
    ]
