# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-31 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0008_leaverequest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecord',
            name='faculty',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIS.Faculty'),
        ),
    ]
