# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0009_auto_20160731_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='SIS.Student')),
            ],
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
        migrations.AddField(
            model_name='selectedsubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='SIS.Subject'),
        ),
    ]
