# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-01 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0010_auto_20160801_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='subject',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='selected_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='SIS.SelectedSubject'),
        ),
    ]
