# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-01 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0011_auto_20160802_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
